version: "3.8"

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4g
        reservations:
          cpus: "0.5"
          memory: 2g

  gielda_service:
    build:
      context: .
      dockerfile: Dockerfile.gielda
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: database
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4g
        reservations:
          cpus: "0.5"
          memory: 2g

  trade_service_1:
    build:
      context: .
      dockerfile: Dockerfile.trade
    depends_on:
      - database
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: database
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      COMPANIES_IDS: "1,2,3"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4g
        reservations:
          cpus: "0.5"
          memory: 2g
  # trade_service_2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.trade
  #   depends_on:
  #     - database
  #   environment:
  #     DB_TYPE: ${DB_TYPE}
  #     DB_HOST: database
  #     DB_PORT: ${DB_PORT}
  #     DB_USER: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_NAME: ${DB_NAME}
  #     COMPANYS_IDS: "4,5,6"

volumes:
  db_data:
